owner: Representaciones-Pedraja
repo: status

sites:
  - name: "Shop"
    url: https://pedraja.es

  - name: "Cloud"
    url: https://cloud.pedraja.es

  - name: "Billing"
    url: https://odoo.pedraja.es

  - name: "Webmail"
    url: https://webmail.pedraja.es

  - name: "Duplicati Backups"
    url: https://backup.pedraja.es

  - name: "Matomo"
    url: https://analytics.pedraja.es

  - name: "Grafana"
    url: https://grafana.pedraja.es


status-website:
  cname: status.pedraja.es
  name: Pedraja Status
  logoUrl: https://pedraja.es/img/logo-1700576909.webp  # ← Pon la URL de tu logo aquí
  introTitle: "Estado de los servicios de **Pedraja**"
  introMessage: Monitoreo en tiempo real de nuestros servicios principales servicios.
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://pedraja.es
    - title: GitHub
      href: https://github.com/Representaciones-Pedraja/status
  
  # Personalización de tema y colores
  theme: light  # Opciones: light, dark, night, ocean
  
  # Ocultar secciones
  favicon: https://pedraja.es/img/favicon.ico
  
  # Personalizar colores (opcional)
  customCSS: |
    body {
      font-family: 'Inter', -apple-system, sans-serif;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }

# Configuración adicional
assignees:
  - representaciones-pedraja  # Para recibir notificaciones de caídas

# Ocultar la sección de licencia del README
i18n:
  footer: Powered by Pedraja.es
  
# Compromisos de uptime
commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "josemanuel@pedraja.es"
