owner: Representaciones-Pedraja
repo: status

# User agent personalizado para evitar bloqueos
user-agent: Mozilla/5.0 (compatible; PedrajaStatus/1.0)

sites:
  - name: "Shop"
    url: https://pedraja.es
    maxResponseTime: 10000

  - name: "Cloud"
    url: https://cloud.pedraja.es
    maxResponseTime: 10000

  - name: "Billing"
    url: https://odoo.pedraja.es
    maxResponseTime: 10000

  - name: "Mail"
    url: mail.pedraja.es
    port: 25
    check: "tcp-ping"

  - name: "Webmail"
    url: https://webmail.pedraja.es
    maxResponseTime: 10000

  - name: "Pdrj"
    url: https://pdrj.es
    maxResponseTime: 10000

  - name: "Duplicati Backups"
    url: https://backup.pedraja.es
    maxResponseTime: 10000

  - name: "Matomo"
    url: https://analytics.pedraja.es
    maxResponseTime: 10000

  - name: "Grafana"
    url: https://grafana.pedraja.es
    maxResponseTime: 10000

  - name: "VPN"
    url: https://vpn.pedraja.es
    maxResponseTime: 10000


status-website:
  cname: status.pedraja.es
  name: Pedraja Status
  logoUrl: https://pedraja.es/img/logo-1700576909.webp 
  favicon: https://pedraja.es/img/favicon.ico
  introTitle: "**Estado de los servicios de Pedraja**"
  introMessage: Monitoreo en tiempo real de nuestros servicios principales.
  theme: light
  
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://pedraja.es
    - title: GitHub
      href: https://github.com/Representaciones-Pedraja/status

# Notificaciones
assignees:
  - JoseManuelPedraja

# Personalización
i18n:
  footer: "© 2024 Pedraja.es"
  
commitMessages:
  commitAuthorName: "Pedraja Status Bot"
  commitAuthorEmail: "josemanuel@pedraja.es"

skipDescriptionIssues: true
skipTopicsIssues: true