owner: Representaciones-Pedraja
repo: status

sites:
  - name: Tienda
    url: https://www.pedraja.es
  - name: Facturacion
    url: https://odoo.pedraja.es
  - name: Cloud
    url: https://cloud.pedraja.es
  - name: Mail
    url: https://webmail.pedraja.es
  - name: Analytics
    url: https://analytics.pedraja.es
  - name: Backups
    url: https://backup.pedraja.es

status-website:
  cname: status.pedraja.es
  logoUrl: https://pedraja.es/img/logo-1700576909.webp  # ← Pon la URL de tu logo aquí
  name: Pedraja Status
  introTitle: "Estado de los servicios de **Pedraja**"
  introMessage: Monitoreo en tiempo real de nuestros servicios principales servicios.
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://www.pedraja.es
    - title: GitHub
      href: https://github.com/Representaciones-Pedraja/status
  
  # Personalización de tema y colores
  theme: dark  # Opciones: light, dark, night, ocean
  
  # Ocultar secciones
  favicon: https://pedraja.es/img/logo-1700576909.webp
  
  # Personalizar colores (opcional)
  customCSS: |
    body {
      font-family: 'Inter', -apple-system, sans-serif;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }

# Configuración adicional
assignees:
  - representaciones-pedraja  # Para recibir notificaciones de caídas

# Ocultar la sección de licencia del README
i18n:
  footer: Powered by Pedraja.es
  
# Compromisos de uptime
commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "josemanuel@pedraja.es"
